### ISSUE TITLE
The missing token "$" in script caused command error.

### ISSUE THREAD

**Issue by blackgear** [othercat/CJKFontScript#2]
`chmod 644 "{LibraryFontsPath}/SourceHanSans.ttc"`
should be
`chmod 644 "${LibraryFontsPath}/SourceHanSans.ttc"`

Both install_SHS-AdobeOfficialSuperOTC.sh and install_SHS-UI.sh share the same problem.

**Comment by ShikiSuen** [comment]
Solid copy. Gonna fix it, ETA 30 minutes. (I'm on the bus)

**Comment by ShikiSuen** [comment]
Issue Solved. Thanks for your feedback.
