### ISSUE TITLE
Firefox 36.0.4出现中文字符粗细不统一，系统10.10.4

### ISSUE THREAD

**Issue by puteulanus** [othercat/CJKFontScript#3]
安装的是ae4210a的SHSUI-GUIFontForYosemite.pkg

浏览器菜单效果
![3ewjv6q ma s7 mz4 1ovu](https://cloud.githubusercontent.com/assets/4849177/7506373/9826e38c-f491-11e4-80db-ad974dc30df1.jpg)

网页显示效果
![87bbd04a-73ba-4649-80ab-dc81394a70e9](https://cloud.githubusercontent.com/assets/4849177/7506397/e9145540-f491-11e4-8b13-c06b036f0892.png)

BTW，我浏览器菜单应该是简体的，但安装之后有些选项却变成繁体了（见上图）
安装YosemiteFactorialChineseGUIFontRecovery.pkg后恢复正常

正常菜单效果
![3a75c19b-977b-4ba4-824a-04af0d87356d](https://cloud.githubusercontent.com/assets/4849177/7506461/c3f466dc-f492-11e4-82f7-1f501bdce3c1.png)

**Comment by ShikiSuen** [comment]
請將 FireFox 簡繁日韓 與 用戶自定義 這幾個語系的字體全都改成思源UI，之後再行測試並反饋情況。

**Comment by puteulanus** [comment]
感谢，修改后显示正常

![03d73330-9931-47f7-b6c5-431ef5097f85](https://cloud.githubusercontent.com/assets/4849177/7506743/82415afc-f496-11e4-8e02-9f7745131c38.png)

![a7ae0343-419d-4b33-91f8-f4b7069f5c77](https://cloud.githubusercontent.com/assets/4849177/7506745/8dab6cca-f496-11e4-8d9e-e9e14cf395b0.png)

这是默认设置
![81d36339-eb29-4468-8db3-0019a4390e59](https://cloud.githubusercontent.com/assets/4849177/7506749/b0d4e7d0-f496-11e4-998a-223e06a7ce44.png)
