### ISSUE TITLE
字体脱节与无法显示bug 反馈

### ISSUE THREAD

**Issue by ikokoo** [othercat/CJKFontScript#4]
![qq20150601-4 2x](https://cloud.githubusercontent.com/assets/12690201/7906041/eb8d7f5e-0855-11e5-8cde-48839a74250c.png)
![qq20150601-5 2x](https://cloud.githubusercontent.com/assets/12690201/7906042/eee1b792-0855-11e5-9727-980bd875fa66.png)

Yosemite 10.10.3 
Macboor air 13"
Issues 1 :excel （2011）工作表无法显示出文字。
Issues 2: 微信Mac版字体向上脱节

**Comment by ShikiSuen** [comment]
Office 2011 不能完美支援 OTF Postscript 字體，請換用目前的 Office 2016：
![image](https://cloud.githubusercontent.com/assets/3164826/7906326/68c49c20-07e6-11e5-9f72-963142acd3f0.png)

至於微信，因為微信的字體 Metrics 顯示是針對華文黑體優化的、而非根據 Apple 的指示來處理（優先且僅針對 Helvetica Neue 來優化），於是可以理解為「微信替華文黑體擦了多餘的屁股」。

**Comment by ShikiSuen** [comment]
關於微信，還有一種可能性就是：微信強制氣泡的縱向尺寸不小於肖像的縱向尺寸。

**Comment by ikokoo** [comment]
感谢你的回复！再次感谢你为此项目做出的努力。谢谢！

**Comment by ShikiSuen** [comment]
不會。

Sent from Outlook

On Sun, May 31, 2015 at 11:51 PM -0700, "ikokoo" notifications@github.com wrote:
感谢你的回复！再次感谢你为此项目做出的努力。谢谢！

---
