### ISSUE TITLE
行高问题

### ISSUE THREAD

**Issue by 7nights** [othercat/CJKFontScript#5]
发现将这个字体用在输入法里的时候，字体上部分会多出来明显的一块空白，使用从 adobe 网站上的链接下载下来的字体会好很多，这是神马原因？

**Comment by ShikiSuen** [comment]
@7nights 我想知道你用官方字體時是否用的是 1.003 版本。要不要再確認一下？（這有助於我排查問題所在）

**Comment by 7nights** [comment]
额我看了一下发现2个字体都不是1.003版本的…… 用 last release 里装出来的字体是 1.002 的。官方的字体貌似是很早以前装的1.000版本，我重新下载一个装试试看。

**Comment by ShikiSuen** [comment]
1.000版本趕緊刪掉，都多舊了…

**Comment by 7nights** [comment]
果然……1.003版本的行高全部崩掉了……看来只能用系统字体或者老版本的了……

**Comment by ShikiSuen** [comment]
你用的是什么输入法？我这边雅虎注音一点问题也没有。

**Comment by ShikiSuen** [comment]
@7nights 实际上这个问题**多半是因为你用的第三方输入法在读取字体高度时读取了不正确的参数**：
![image](https://cloud.githubusercontent.com/assets/3164826/8154163/67327d0a-12f4-11e5-8314-f87276fe69c7.png)

**Comment by 7nights** [comment]
鼠须管、搜狗、百度……

**Comment by ShikiSuen** [comment]
三個輸入法都有這毛病的話我也是醉了。
關於鼠鬚管，請 @lotem @kunki 二位研讀一下我上一條回覆當中徵引的來自小林劍的呼籲。

**Comment by lotem** [comment]
我是字體外行，所以對這些不太明白
就鼠鬚管來說，沒有用到專門處理字體的技術，輸入法候選窗通過 [NSFont fontWithDescriptor: size:] 這個 API 獲取字體，用於繪製 NSAttributedString

**Comment by ShikiSuen** [comment]
To @kenlunde >

@lotem claims that he uses [NSFont fontWithDescriptor: size:] API to obtain the font to draw NSAttributedString. Meanwhile, @7nights claims that bosh SHS 1.003 and SHS UI has problem regarding the unnecessary blank space above the candidate texts of RIME IME.

To @7nights >

Please provide screenshots regarding this issue in RIME. (請針對鼠鬚管和目前版本的思源黑體官方版本的相容性問題提供擷圖)

**Comment by 7nights** [comment]
## Source Han Sans SC Regular: 

**鼠须管：**
 ![image](https://cloud.githubusercontent.com/assets/3193621/8180094/247d9c14-144e-11e5-83b9-26cc1bffd2d2.png)

**搜狗：** 
![image](https://cloud.githubusercontent.com/assets/3193621/8180202/dc94c8d6-144e-11e5-92e1-b573eb4e2eda.png)

![image](https://cloud.githubusercontent.com/assets/3193621/8180113/4313667c-144e-11e5-9ad6-fdc542cbd9d5.png)

## Hiragino Sans GB W3:

**鼠须管：**
 ![image](https://cloud.githubusercontent.com/assets/3193621/8180169/a8cc415a-144e-11e5-87cd-3796fcca9da1.png)

**搜狗：**
 ![image](https://cloud.githubusercontent.com/assets/3193621/8180219/f4a9773c-144e-11e5-882d-c2aa44eecfb3.png)

**Comment by ShikiSuen** [comment]
I have curiosity that why RIME and Sougou presents different heights...

to @Kenlunde >
Looks like @lotem does not know how to read correct metrics from a font for layout purposes.
I translated what he claimed in my last reply, could you please provide any suggestions to him?

**Comment by ShikiSuen** [comment]
Since I mentioned that Hiragino Sans GB W3 looks fine with both RIME and Sougou,
I guessed that these Input Methods should probably read sTypoAscender & sTypoDescender instead of reading the Ascender and descender from HHEA.

**Comment by ShikiSuen** [comment]
Since I mentioned that Hiragino Sans GB W3 looks fine with both RIME and Sougou,
I guessed that these Input Methods should probably read sTypoAscender & sTypoDescender from OS/2 instead of reading the Ascender and descender from HHEA.

**Comment by 7nights** [comment]
@ShikiSuen 高度不一样大概是因为搜狗有一个云输入功能？云输入功能会在云词汇右上角加一朵小云，大概是受行高影响，这朵小云在1.003版本的字体下飞得很高……

![image](https://cloud.githubusercontent.com/assets/3193621/8180856/ba47f5a0-1453-11e5-89f9-5a40a2be3bf7.png)

![image](https://cloud.githubusercontent.com/assets/3193621/8180869/db984b6a-1453-11e5-9ec5-f53111ee33f0.png)

估计就是一个问题造成的 (/ω＼)

**Comment by kenlunde** [comment]
Apologies for the delay in responding. In my experience, 1) the most difficult line to typeset is the very first line, which is practically all UI elements; and 2) the OSes are notorious for being hard-wired to work well only for the fonts that are intended to be used for their UIs. "https://github.com/adobe-fonts/source-han-sans/issues/2" does not mean that other fonts that do not behave in similar ways are wrong. It means that the layout engine for the UI was poorly implemented, or references inappropriate fields in one or more tables in the font.

**Comment by ShikiSuen** [comment]
Thanks for Ken's reply. (I modified a hyperlink in his reply in order to reference to the issue he really want to reference)
